apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: etl-users-python
  namespace: spark
spec:
  type: Python
  mode: cluster
  image: "luanmoreno/spark-operator:latest"
  imagePullPolicy: Always
  mainClass: luanmoreno.Users
  mainApplicationFile: "local:///app/etl-users.py"
  arguments:
    - /app/user_names.csv
  sparkVersion: "2.4.5"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 2.4.5
    serviceAccount: spark-sparkoperator
  executor:
    cores: 1
    instances: 7
    memory: "512m"
    labels:
      version: 2.4.5
